name: Go CI

on:
  push:
    branches: ['**']
    paths:
      - 'go/**'
      - '.github/workflows/go-ci.yml'
      - '.github/workflows/reusable-go.yml'
  pull_request:
    branches: ['**', '!main']
    paths:
      - 'go/**'
      - '.github/workflows/go-ci.yml'
      - '.github/workflows/reusable-go.yml'

jobs:
  call:
    uses: ./.github/workflows/reusable-go.yml
