name: Python CI

on:
  push:
    branches: ['**']
    paths: ['python/**']
  pull_request:
    branches: ['**', '!main']
    paths: ['python/**']

jobs:
  call:
    uses: ./.github/workflows/reusables/python.yml
