name: Python CI

on:
  push:
    branches: ['**']
    paths:
      - 'python/**'
      - '.github/workflows/python-ci.yml'
      - '.github/workflows/reusable-python.yml'
  pull_request:
    branches: ['**', '!main']
    paths:
      - 'python/**'
      - '.github/workflows/python-ci.yml'
      - '.github/workflows/reusable-python.yml'

jobs:
  call:
    uses: ./.github/workflows/reusable-python.yml
