name: Reusable Python CI

on:
  workflow_call:

jobs:
  python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('python/requirements.txt') }}

      - run: |
          cd python
          pip install -r requirements.txt

      - name: Lint
        continue-on-error: true
        run: |
          cd python
          pip install flake8
          flake8

      - name: Test
        run: |
          cd python
          pip install pytest
          pytest
