name: Rust CI

on:
  push:
    branches: ['**']
    paths:
      - 'rust/**'
      - '.github/workflows/rust-ci.yml'
      - '.github/workflows/reusable-rust.yml'
  pull_request:
    branches: ['**', '!main']
    paths:
      - 'rust/**'
      - '.github/workflows/rust-ci.yml'
      - '.github/workflows/reusable-rust.yml'

jobs:
  call:
    uses: ./.github/workflows/reusable-rust.yml
